import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { resolveConfig } from "../config.js";

export const baInitSchema = z.object({ projectRoot: z.string() });

const DIRS = [
  "01-vision", "02-stakeholders/personas", "03-requirements/functional",
  "03-requirements/non-functional", "04-use-cases", "05-stories",
  "06-analysis", "07-changelog",
];

const FILES: Record<string, string> = {
  "_config.yml": "docsRoot: docs/ba\nidStart: 1\n",
  "_index.md": "# BA Index\n\n_Status dashboard is generated by ba_status._\n",
  "01-vision/vision.md": "# Vision\n\n## Problem\n\n## Goals\n\n## Success Metrics\n",
  "01-vision/glossary.md": "# Glossary\n\n| Term | Definition |\n|------|------------|\n",
  "06-analysis/traceability.md": "# Traceability Matrix\n\n_Generated by ba_build_traceability._\n",
  "06-analysis/gap-report.md": "# Gap Report\n\n_Generated by ba_analyze_gaps._\n",
  "06-analysis/risks.md": "# Risks\n\n| ID | Risk | Impact | Mitigation |\n|----|------|--------|------------|\n",
  "06-analysis/assumptions.md": "# Assumptions\n\n| ID | Assumption | Status |\n|----|------------|--------|\n",
  "07-changelog/CHANGELOG.md": "# Requirement Changelog\n\n",
};

export function baInit(input: { projectRoot: string }): { created: string[]; docsRoot: string } {
  const { docsRoot } = resolveConfig(input.projectRoot);
  const created: string[] = [];
  for (const d of DIRS) mkdirSync(join(docsRoot, d), { recursive: true });
  for (const [rel, content] of Object.entries(FILES)) {
    const p = join(docsRoot, rel);
    if (!existsSync(p)) { writeFileSync(p, content, "utf8"); created.push(rel); }
  }
  return { created, docsRoot };
}
